image: continuumio/anaconda3
stages:
  - Test

Search Wally from images:
  stage: Test
  script:
    - conda update -n base -c defaults conda
    - conda create -n waldo python=3.5.3 pip
    - conda init bash
    - . ~/.bashrc
    - conda activate waldo
    - conda install -y tensorflow matplotlib keras pillow requests
    - pip install rpyc==3.3.0
    - cd modules && export PYTHONPATH=/usr/lib/python3.7/site-packages:`pwd`:`pwd`/slim
    - cd ..
    - ./test_AI.py
  artifacts:
    when: on_success
    paths:
      - heads/*.jpg