from robot import *
from image import *

print("Bereiten sie die Webcam vor.")
print("Als Gruppe vor die Kamera stehen, dann enter drücken")
input()
Gruppe = Foto()
print("Einzelne Person vor Kamera stellen, enter drücken")
input()
Person = Foto()
print("Das Gruppenfoto ausdrucken (Datei hier: {}) und die Breite in cm eingeben".format(Gruppe))
Breite = int(input())
print("Roboter bereitstellen, dann enter drücken")
input()
print("Finde Person...")
Pixel = Finde_Person(Person, Gruppe)
Zeige_Foto(Markieren(Pixel, Gruppe))
Koordinaten = Konvertieren(Pixel, Vergrössern(Gruppe, Breite))
Koordinaten = [Koordinaten[0] + ROBOT_ARM_SIZE / 10, Koordinaten[1], Koordinaten[2] + ROBOT_ARM_SIZE / 10, Koordinaten[3]]
Strecke, Winkel = Hypotenuse2(Koordinaten)

print("Fahre Roboter")
Rechts(Winkel)
Vorwärts(Strecke - ROBOT_ARM_SIZE/10)
Zeigen()
print("Ziel erreicht")
Sprich("Person gefunden")
print("enter drücken um den Roboter zurückkehren zu lassen")
input()
Nicht_Zeigen()
Rückwärts(Strecke - ROBOT_ARM_SIZE/10)
Links(Winkel)
